# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WorkingBeez' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Fabric'
    pod 'Digits'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
  # Pods for WorkingBeez

end
